language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

before_install:
  - go get -v github.com/mattn/goveralls

script:
  - go build
  - go test -covermode=atomic -coverprofile=cover.profile -gcflags=-l -v -race ./...
  - goveralls -coverprofile=cover.profile -service=travis-ci

notifications:
  email:
    recipients:
      - raskarpour@gmail.com
    on_success: change
    on_failure: always